### ISSUE TITLE
Using time on x axis (POSIXct)

### ISSUE THREAD

**Issue by jcpsantiago** [kassambara/ggpubr#17]
Not sure if this is by design, but ggpubr won't format axis ticks correctly when given a datetime (POSIXct) column as input.

The `fulldate` column used in the plots below is of class 
```
> class(n_hours$fulldate)
[1] "POSIXct" "POSIXt" 
```
and has the format `"2017-01-01 20:45:00 UTC"`

Plot made with ggpubr:
```
n_hours %>%
  ggline(x = "fulldate", y = "value",
         group = "ID", add = "mean",
         x.text.angle = 25)
```
![rplot](https://user-images.githubusercontent.com/789796/28866624-c839d89c-7773-11e7-869e-a24353c61ab5.jpeg)

and the same data directly with ggplot:
```
n_hours %>%
  ggplot(aes(x = fulldate, y = value, group = ID)) +
  stat_summary(aes(group = ID), geom = "line", fun.y = mean, size = 0.6)
```
![rplot01](https://user-images.githubusercontent.com/789796/28866661-e88d8850-7773-11e7-9897-f0c665a896c1.jpeg)

**Comment by kassambara** [comment]
Should work now, thanks.

**Comment by jcpsantiago** [comment]
Thanks for looking into it! It's still not working for me with your latest commit. ggpubr is still converting the data to numeric.

**Comment by kassambara** [comment]
would you please provide a reproducible R script with a demo data set?

To include data in a question, use dput() to generate the R code to recreate it. For example, to recreate the mtcars dataset in R, I’d perform the following steps:

1. Run dput(mtcars) in R
2. Copy the output
3. In your reproducible script, type mtcars <- then paste.

Thanks

**Comment by jcpsantiago** [comment]
Here you go:
[rep_script.txt](https://github.com/kassambara/ggpubr/files/1194424/rep_script.txt)

**Comment by kassambara** [comment]
Thank you.

Should work now. dplyr >= 0.7.1 required

**Comment by jcpsantiago** [comment]
Great! Thank you man ;)
