### ISSUE TITLE
Specify label.y.npc in facets when using comparisons

### ISSUE THREAD

**Issue by toothpicky** [kassambara/ggpubr#190]
I am having the problem identified here: https://github.com/kassambara/ggpubr/issues/50#issuecomment-345327584

But the thread was closed and I want to re-open it. Specifically, I want to use label.y.npc and not label.y because the scales='free_y' option

**Comment by erosix** [comment]
Same problem here. The top pvalue bar is overlapping with the top of the plot and get cut out. So i need to set the y value also when I have different y axis values in the two facets, any idea how?

**Comment by pavitraviswanath** [comment]
I have the same issue as well. Have you'll been able to figure it out? For example, this is how my plots look:
![image](https://user-images.githubusercontent.com/43428054/77834737-7550d780-710c-11ea-847e-aeb7aed3ca7a.png)

**Comment by erosix** [comment]
Unfortunately not, I had to do separate plots for each facet and for each set the ylim for the plot and the label.y values for the pvalues manually.

**Comment by tamburinif** [comment]
Having this issue as well, it would be great to have a fix...

**Comment by kassambara** [comment]
duplicates of #136 .

Using the combination of the ggplot functions `scale_y_continuous()` and `expansion()` should solve this issue; see example of R codes at:  [GGPLOT Facet: How to Add Space Between Labels on the Top of the Chart and the Plot Border](https://www.datanovia.com/en/blog/ggplot-facet-how-to-add-space-between-labels-on-the-top-of-the-chart-and-the-plot-border/)

**Comment by pavitraviswanath** [comment]
I am still having the same issue despite adding p <- p + scale_y_continuous(expand = expansion(mult = c(0.1, 0.14))) before the stat_compare_meanst function.
In addition, when I tey to add p-values computed using r-statix, I get the error saying y.position is not defined even though I do. This is my code:

stat.test <- rdf %>% add_y_position()
group_by(variable2) %>%
t_test(value~collection)
stat.test
p <- ggplot(data = rdf, mapping = aes(x = variable2, y = value, fill =collection))
p <- p + geom_violin(alpha=0.3, scale="width", position = position_dodge(width=1), size=0.5)
p <- p + geom_boxplot(alpha=0.7, outlier.shape=NA, facet.by="variable2",  position = position_dodge(1), scales="free")
p <- p + geom_point(position = position_jitterdodge(jitter.width=0.1,jitter.height=0, dodge.width = 1))
#p <- p + geom_jitter(position=position_jitter(width=0.1,height=0))
p <- p + theme_bw()
p <- p + theme(axis.text.x = element_blank())
p <- p + scale_fill_viridis_d(option = "D")
p <- p + facet_wrap(~variable2, scales="free", ncol=5)
p <- p + scale_y_continuous(expand = expansion(mult = c(0.1, 0.14)))
p <- p + stat_compare_means(method = "anova", size=3, hjust=0.7, label.y.npc = 'top', family="Arial", fontface="bold") 
#p <- p + stat_pvalue_manual(stat.test, label="p", y.position = "yloc") 
#p <- p + stat_compare_means(comparisons = my_comparisons, size=3, family= "Arial", face= "bold")
p <- p + labs(title="Extracellular Panel Analysis")
p <- p + ylab("% Live Cells") + xlab(" ")
p <- p + theme(text=element_text(family="Arial", face = "bold"))
p


![image](https://user-images.githubusercontent.com/43428054/93408900-e919a480-f852-11ea-9675-71821d53b92c.png)
